//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFS_Backup_Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class BackupUser
    {
        public BackupUser()
        {
            this.BackupApplicationLogs = new HashSet<BackupApplicationLog>();
            this.Backups = new HashSet<Backup>();
        }
    
        public string UserName { get; set; }
        public string ComputerName { get; set; }
        public int BackupUserSys { get; set; }
    
        public virtual ICollection<BackupApplicationLog> BackupApplicationLogs { get; set; }
        public virtual ICollection<Backup> Backups { get; set; }
    }
}
