//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFS_Backup_Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class BackupFile
    {
        public string FilePath { get; set; }
        public int BackupSys { get; set; }
        public int BackupFileSys { get; set; }
    
        public virtual Backup Backup { get; set; }
    }
}
