//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFS_Backup_Utility
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TFSBackupEntities : DbContext
    {
        public TFSBackupEntities()
            : base("name=TFSBackupEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BackupApplicationLog> BackupApplicationLogs { get; set; }
        public virtual DbSet<BackupFile> BackupFiles { get; set; }
        public virtual DbSet<BackupLog> BackupLogs { get; set; }
        public virtual DbSet<Backup> Backups { get; set; }
        public virtual DbSet<BackupUser> BackupUsers { get; set; }
    }
}
