//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFS_Backup_Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class Backup
    {
        public Backup()
        {
            this.BackupFiles = new HashSet<BackupFile>();
            this.BackupLogs = new HashSet<BackupLog>();
        }
    
        public string BackupName { get; set; }
        public System.DateTime BackupDateTime { get; set; }
        public int BackupUserSys { get; set; }
        public int BackupSys { get; set; }
        public bool Successful { get; set; }
    
        public virtual ICollection<BackupFile> BackupFiles { get; set; }
        public virtual ICollection<BackupLog> BackupLogs { get; set; }
        public virtual BackupUser BackupUser { get; set; }
    }
}
